# Generated by Django 3.2.6 on 2021-08-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField(max_length=15)),
                ('Physics', models.IntegerField(max_length=15)),
                ('Chemistry', models.IntegerField(max_length=15)),
                ('Biology', models.IntegerField(max_length=15)),
                ('English', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('RoleNo', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('Class', models.CharField(max_length=120)),
                ('Mobile', models.CharField(max_length=15)),
                ('Address', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='studentacademics',
            name='RoleNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.studentinfo'),
        ),
    ]
