# Generated by Django 3.2.6 on 2021-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210819_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='RoleNo',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
