# Generated by Django 3.2.6 on 2021-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_studentinfo_roleno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='Biology',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='Chemistry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='English',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='Maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='Physics',
            field=models.IntegerField(),
        ),
    ]
